### ISSUE TITLE
Not specifying a region can lead to confusing error message

### ISSUE THREAD

**Issue by tijmenb** [newrelic/deployment-marker-action#17]
Over the last couple of days I spent a lot longer than I'd like to admit trying to set up this GitHub Action. The reason for this is that I used the [first example from the README](https://github.com/newrelic/deployment-marker-action#example-usage). I kept running into a `403 response returned` error:

<img width="968" alt="Screenshot 2021-11-03 at 09 58 26" src="https://user-images.githubusercontent.com/233676/140032524-5bad5e0a-6810-4de9-8920-6592be9fd6e9.png">

At first I assumed this was due to a incorrect API key (so I tried a Ingestion key and a legacy REST key). Eventually I figured out that because our account is EU, the API request fails because it defaults the region to US.

To avoid other people running into the same issue, I wonder if the workflow could output a more informative error message for this `403`? Or alternatively, could we make the `region` required?

**Comment by Ahmed-Sermani** [comment]
I ran into the same issue and spent a lot of time thinking that the problem in the API key.

**Comment by kidk** [comment]
Thanks @Ahmed-Sermani and @tijmenb  I'll check with team to see if we can improve this.

**Comment by kidk** [comment]
@tijmenb and @Ahmed-Sermani As we can't detect if that's the problem we are thinking of improving the error message "403 response returned - please check you API key and region". Do you think that will be enough?

**Comment by tijmenb** [comment]
Thanks @kidk! Yeah that will definitely be useful. Here's a PR that adds the region to the examples in the README: https://github.com/newrelic/deployment-marker-action/pull/30

Together with your proposal I think it'll probably be sufficient.

**Comment by kidk** [comment]
Awesome, thanks a lot @tijmenb ❤️

**Comment by kidk** [comment]
Fix has been deployed, thanks @NSSPKrishna and @tijmenb
