### ISSUE TITLE
Recommendation for deployment markers in containerized environment (Fargate)

### ISSUE THREAD

**Issue by josh803316** [newrelic/deployment-marker-action#18]
I'm using Github actions to deploy new versions of our Fargate tasks into our Production cluster when we "release".  NewRelic is being used to track metrics and logs for these containers, but I was wondering what would make sense in terms of displaying deployment versions / demarcation lines -- similar to what is being done for the APM app deployments.  I'm not sure if this is possible but I was hoping for guidance on seeing these lines in the "Summary" view for the production containers.

**Comment by kidk** [comment]
Hi @josh803316 

This is now possible with the new version of the deployment-marker-action. New Relic has recently released the next iteration of our deployment marker functionality: https://newrelic.com/blog/nerdlog/change-tracking

You should now be able to set deployment markers or change markers on any entity within New Relic, including Fargate based on the GUID. There's some additional examples on our docs: https://docs.newrelic.com/docs/change-tracking/ci-cd/change-tracking-github-actions/

Hope this helps. Let us know if you have any questions.
