### ISSUE TITLE
Question: How to solve a Fatal Error "maximum retries reached: An error occurred resolving this field"?

### ISSUE THREAD

**Issue by ValeryiaLukyanava** [newrelic/deployment-marker-action#36]
Hello! Could you help me, please? 
The job `newrelic/deployment-marker-action@v2.2.0` was started several times with incorrect New Relic API keys. 
Now the keys are correct, but I see a Fatal Error: 
`Error:  level=fatal msg="maximum retries reached: An error occurred resolving this field"`

**Comment by ValeryiaLukyanava** [comment]
Sorry for disturbing. The question is no longer relevant: the problem has been solved.

**Comment by suho** [comment]
@ValeryiaLukyanava I'm having the same issue, could you share with me how to resolve this?
