### ISSUE TITLE
Action fails with "Unrecognized named-value 'github'"

### ISSUE THREAD

**Issue by jerelmiller** [newrelic/deployment-marker-action#6]
First of all, SUPER cool that there is now an officially supported github action!

I decided to try it out, but unfortunately my action fails to run with the following error in the setup job:

```
##[error](Line: 25, Col: 18): Unrecognized named-value: 'github'. Located at position 1 within expression: github.actor
##[error]Fail to load /home/runner/work/_actions/newrelic/deployment-marker-action/master/action.yaml
```

If I'm reading this right, perhaps the description for the `user` input is trying to parse a value rather than using the literal string value?

**Comment by sanderblue** [comment]
Hi @jerelmiller! Big thanks for giving it a try and reporting. I was also able to reproduce this. I'll get a fix going 🙂

**Comment by jerelmiller** [comment]
Awesome!! I look forward to using it :)

**Comment by AnilVhatkar1130** [comment]
Hi I'm getting same error 
Error: AnilVhatkar1130/podcast-generator/main/action.yml (Line: 14, Col: 16): Unrecognized named-value: 'github'. Located at position 1 within expression: github.actor
Error: AnilVhatkar1130/podcast-generator/main/action.yml (Line: 18, Col: 16): Unrecognized named-value: 'github'. Located at position 1 within expression: github.actor

**Comment by AnilVhatkar1130** [comment]
Error: AnilVhatkar1130/podcast-generator/main/action.yml (Line: 14, Col: 16): Unrecognized named-value: 'github'. Located at position 1 within expression: github.actor
Error: AnilVhatkar1130/podcast-generator/main/action.yml (Line: 18, Col: 16): Unrecognized named-value: 'github'. Located at position 1 within expression: github.actor
Error: Failed to load AnilVhatkar1130/podcast-generator/main/action.yml
