### ISSUE TITLE
Question: How to resolve the error "maximum retries reached: An error occurred resolving this field"

### ISSUE THREAD

**Issue by suho** [newrelic/deployment-marker-action#60]
I'm using `newrelic/deployment-marker-action@v2.5.0` and seeing this error:

```
level=fatal msg="maximum retries reached: An error occurred resolving this field"
Error:  level=fatal msg="maximum retries reached: An error occurred resolving this field"
```

Could you help me to check on what I'm doing wrong? Many thanks!

**Comment by suho** [comment]
This issue is related to the wrong `guid` value. I found it with the CLI (or from the settings page)

**Comment by coreyd-valcre** [comment]
@suho How did you resolve this? I have 2 jobs running side by side that both get a GUID from 2 different apps then both run the markers. One always fails with this and another succeeds using the same composite actions.
